apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-server
  template:
    metadata:
      labels:
        app: file-server
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: uploads-volume
              mountPath: /usr/share/nginx/html/uploads # Nginx's default static file serving location
      volumes:
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: uploads-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: file-server-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30088
  selector:
    app: file-server
