apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hasura
    hasuraService: custom
  name: hasura
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hasura
    spec:
      containers:
        - image: hasura/graphql-engine:v2.44.0
          imagePullPolicy: IfNotPresent
          name: hasura
          env:
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              value: aFVeqGfcVsDTpS7efXQZ1rlMyIJugSBJ
            - name: HASURA_GRAPHQL_DATABASE_URL
              value: postgres://postgres:C4cJNWmrKa@my-release-postgresql:5432/vvims
            ## enable the console served by server
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: "true"
            ## enable debugging mode. It is recommended to disable this in production
            - name: HASURA_GRAPHQL_DEV_MODE
              value: "true"
            - name: HASURA_GRAPHQL_CONSOLE_ASSETS_DIR
              value: /srv/console-assets
            - name: HASURA_GRAPHQL_JWT_SECRET
              value: '{"type": "HS256", "key": "aP3x!9Qz@2Lk#8Vw$7Jm^5Bn&4Xy*6Tg"}'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources: {}
