apiVersion: v1
kind: Service
metadata:
  name: hasura
  labels:
    app: hasura
spec:
  type: NodePort
  selector:
    app: hasura
  ports:
  - protocol: TCP
    port: 8080          
    targetPort: 8080   
    nodePort: 30011   

# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: hasura
#   name: hasura
#   namespace: default
# spec:
#   ports:
#   - protocol: TCP
#     port: 8080
#     targetPort: 8080
#   selector:
#     app: hasura
#   type: LoadBalancer

# apiVersion: v1
# kind: Service
# metadata:
#   name: hasura
# spec:
#   selector:
#     app: hasura
#   ports:
#   - port: 80
#     targetPort: 8080

