apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-pv
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath: # Use a suitable volume type for your environment
    path: /home/cnps/downloads # Adjust path as necessary for your setup