
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vvims-deployment
  labels:
    app: vvims
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vvims
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: vvims
    spec:
      containers:
        - name: ntchinda-giscard-new-vvims
          image: registry.hf.space/ntchinda-giscard-vvims-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7860
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: vvims-secret
                  key: x-secret-key
            - name: ROBOFLOW_KEY
              valueFrom:
                secretKeyRef:
                  name: vvims-secret
                  key: roboflow-key
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: vvims-secret
                  key: aws-access-key
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: vvims-secret
                  key: aws-secret-key
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: vvims-configmap
                  key: database-url
          # resources: {}
          volumeMounts:
            - name: uploads-volume
              mountPath: /app/uploads

      volumes:
         - name: uploads-volume
           persistentVolumeClaim:
             claimName: uploads-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: vvims-service
  labels:
    app: vvims
spec:
  type: NodePort
  selector:
    app: vvims
  ports:
  - protocol: TCP
    port: 7860       # The port that the Service will expose
    targetPort: 7860  # The port on the container that the Service will forward to
    nodePort: 30000  # The port on each node that will forward traffic to the Service

# apiVersion: v1
# kind: Service
# metadata:
#   name: vvims-service
# spec:
#   selector:
#     app: vvims
#   ports:
#   - port: 80
#     targetPort: 7860
