"""Sync database state

Revision ID: a4070a0f9217
Revises: 9dd3953f0468
Create Date: 2024-09-13 10:43:38.714987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4070a0f9217'
down_revision: Union[str, None] = '9dd3953f0468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spatial_ref_sys')
    op.add_column('agencies', sa.Column('city', sa.String(), nullable=False))
    op.add_column('agencies', sa.Column('region', sa.String(), nullable=False))
    op.add_column('agencies', sa.Column('office', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'agencies', ['id'])
    op.add_column('companies', sa.Column('city', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('region', sa.String(), nullable=False))
    op.add_column('employees', sa.Column('company_id', sa.UUID(), nullable=False))
    op.add_column('employees', sa.Column('agency_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'employees', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'agencies', ['agency_id'], ['id'])
    op.drop_constraint('visits_host_service_fkey', 'visits', type_='foreignkey')
    op.create_foreign_key(None, 'visits', 'services', ['host_service'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.create_foreign_key('visits_host_service_fkey', 'visits', 'employees', ['host_service'], ['id'])
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'agency_id')
    op.drop_column('employees', 'company_id')
    op.drop_column('companies', 'region')
    op.drop_column('companies', 'city')
    op.drop_constraint(None, 'agencies', type_='unique')
    op.drop_column('agencies', 'office')
    op.drop_column('agencies', 'region')
    op.drop_column('agencies', 'city')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
